export const contactEmail = 'dev.wlgns@gmail.com';
export const locales = ['en', 'ko'];

export const copy = {
  "en": {
    "siteTitle": "JIHOON — Backend Engineering & Application Security",
    "description": "Jihoon’s engineering portfolio: PostgreSQL transactions, authentication, authorization, API security, data synchronization, and regression testing across independent software projects.",
    "nav": [
      "Projects",
      "Engineering",
      "Contact"
    ],
    "skip": "Skip to content",
    "menu": "Menu",
    "closeMenu": "Close menu",
    "home": "Home",
    "eyebrow": "JIHOON / ENGINEERING PORTFOLIO",
    "headline": [
      "Backend engineering.",
      "Security by design."
    ],
    "intro": "I develop backend systems for independent software projects, focusing on data consistency, authentication, authorization, and application security.",
    "viewWork": "View project experience",
    "contact": "Get in touch",
    "focus": [
      "Backend systems",
      "Security boundaries",
      "Meaningful tests"
    ],
    "selectedLabel": "01 / PROJECT EXPERIENCE",
    "selectedTitle": "Apps and tools I’m building",
    "selectedIntro": "Travel memories, whiskey collections, daily learning, and financial research. Explore each product and the engineering behind it.",
    "allWork": "View all projects",
    "readCase": "View technical case study",
    "viewProject": "Explore project",
    "approachLabel": "02 / ENGINEERING EXPERIENCE",
    "approachTitle": "Technical depth,\nacross the stack.",
    "approachIntro": "A closer look at the backend and security concerns implemented across these projects.",
    "approachItems": [
      [
        "Explicit contracts",
        "Define valid inputs, authorization requirements, state transitions, and retry behavior before treating an API as complete."
      ],
      [
        "Failure-oriented review",
        "Review concurrent requests, expired credentials, partial failures, and conflicting data as part of the implementation."
      ],
      [
        "Traceable verification",
        "Connect a change to a regression test and a recorded result. State the tested environment and remaining integration work."
      ]
    ],
    "moreLabel": "03 / ADDITIONAL PROJECTS",
    "moreTitle": "Development & exploration",
    "moreIntro": "Game development and an earlier learning application.",
    "ctaLabel": "CONTACT",
    "ctaTitle": "Let’s discuss the role.",
    "ctaText": "For hiring conversations, technical interviews, and collaboration.",
    "footer": "Backend engineering & application security.",
    "backTop": "Back to top",
    "workTitle": "Apps, tools, and experiments",
    "workIntro": "Six projects across travel, personal collections, learning, financial research, and games. Each project introduces the product before examining its design, implementation, and verification.",
    "archived": "Archive",
    "contactTitle": "Contact",
    "contactIntro": "For backend engineering opportunities, technical interviews, or project collaboration, please reach out by email.",
    "emailLabel": "EMAIL",
    "contactNote": "My project experience centers on authentication and authorization, database consistency, API boundaries, and automated verification.",
    "contactTopics": [
      "Backend engineering",
      "Application security",
      "Software development"
    ],
    "projectLabel": "PROJECT NOTES",
    "caseLabel": "ENGINEERING CASE STUDY",
    "overview": "Project context",
    "problem": "Engineering problem",
    "decision": "Design decision",
    "implementation": "Implementation",
    "tradeoff": "Design considerations",
    "verification": "Verification",
    "boundary": "Implementation status",
    "stack": "TECHNOLOGY",
    "status": "STATUS",
    "process": "DEVELOPMENT",
    "processValue": "Independent project · AI-assisted",
    "evidenceLabel": "VERIFICATION CONTEXT",
    "evidenceNote": "Based on source code, regression tests, and development checkpoints reviewed September 5–6, 2026. Test results refer to the environment and checkpoint stated in each case.",
    "returnWork": "Back to all projects",
    "nextProject": "Next project",
    "notFoundTitle": "This page isn’t here.",
    "notFoundText": "Head back to the project collection to keep exploring.",
    "heroNote": "Python · TypeScript · PostgreSQL · Firebase",
    "heroProfile": "BACKEND DEVELOPMENT / APPLICATION SECURITY",
    "aboutLabel": "04 / DEVELOPMENT PRACTICE",
    "aboutTitle": "From requirements to verification",
    "aboutText": "I use AI throughout implementation, debugging, and code review. My project work includes defining product requirements, iterating on behavior, and requesting verification of failure paths. The case studies document the resulting engineering decisions and evidence.",
    "investigationsLabel": "RELATED ENGINEERING WORK",
    "investigationsTitle": "Additional implementation details",
    "challengeLabel": "Scenario",
    "solutionLabel": "Control",
    "checkLabel": "Verification",
    "strengthsLabel": "APPLIED IN THIS PROJECT",
    "profileLabel": "PROJECT FOCUS",
    "reuseLabel": "REUSABLE ENGINEERING ASSETS",
    "reuseTitle": "Code preserved with its context",
    "reuseText": "The retired math application is organized into six feature collections with original source, dependency maps, related tests, and known limitations. A separate Dart import-boundary checker includes usage examples and self-tests. These are maintained as adaptation references; adoption in another active product is not yet established.",
    "reuseLink": "View the archive and reuse approach",
    "productLabel": "THE PRODUCT",
    "workflowLabel": "The user experience",
    "technicalLabel": "Engineering case",
    "invariantLabel": "The condition the system must preserve",
    "flowLabel": "How the implementation works",
    "scenariosLabel": "Scenarios and expected behavior",
    "scenarioLabel": "Scenario",
    "expectedLabel": "Expected behavior / recorded result"
  },
  "ko": {
    "siteTitle": "JIHOON — 백엔드 개발 · 애플리케이션 보안",
    "description": "이지훈의 개발 포트폴리오. 개인 프로젝트에서 구현한 PostgreSQL 트랜잭션, 인증·인가, API 보안, 데이터 동기화와 회귀 테스트를 소개합니다.",
    "nav": [
      "프로젝트",
      "기술 경험",
      "연락처"
    ],
    "skip": "본문으로 이동",
    "menu": "메뉴",
    "closeMenu": "메뉴 닫기",
    "home": "홈",
    "eyebrow": "JIHOON / ENGINEERING PORTFOLIO",
    "headline": [
      "백엔드 개발,",
      "보안을 고려한 설계."
    ],
    "intro": "데이터 정합성, 인증과 권한 제어, 애플리케이션 보안을 중심으로 개인 서비스의 백엔드를 개발하고 있습니다.",
    "viewWork": "프로젝트 경험 보기",
    "contact": "연락하기",
    "focus": [
      "백엔드 시스템",
      "보안 경계",
      "실효성 있는 테스트"
    ],
    "selectedLabel": "01 / PROJECT EXPERIENCE",
    "selectedTitle": "만들고 있는 앱과 도구",
    "selectedIntro": "여행의 기억, 위스키 취향, 매일의 학습과 투자 연구. 각 프로젝트가 어떤 제품인지, 그 안을 어떻게 구현했는지 소개합니다.",
    "allWork": "전체 프로젝트",
    "readCase": "기술 사례 자세히 보기",
    "viewProject": "프로젝트 자세히 보기",
    "approachLabel": "02 / ENGINEERING EXPERIENCE",
    "approachTitle": "프로젝트에서 쌓은\n기술 경험.",
    "approachIntro": "각 프로젝트에 적용한 백엔드 설계와 보안 검증을 주제별로 정리했습니다.",
    "approachItems": [
      [
        "명확한 인터페이스 계약",
        "허용할 입력과 접근 권한, 상태 변경 조건, 재시도 동작을 구체적으로 정의합니다."
      ],
      [
        "실패 상황을 포함한 검토",
        "동시 요청, 만료된 인증 정보, 작업 중단과 데이터 충돌을 구현 과정에서 함께 검토합니다."
      ],
      [
        "근거를 남기는 검증",
        "변경 사항을 회귀 테스트와 실행 기록에 연결하고, 검증 환경과 남은 통합 작업을 명시합니다."
      ]
    ],
    "moreLabel": "03 / ADDITIONAL PROJECTS",
    "moreTitle": "그 밖의 개발 경험",
    "moreIntro": "게임 개발과 이전에 진행한 학습 애플리케이션입니다.",
    "ctaLabel": "CONTACT",
    "ctaTitle": "채용 및 협업 문의",
    "ctaText": "백엔드 개발 직무와 기술 면접, 프로젝트 협업에 관한 연락을 기다립니다.",
    "footer": "백엔드 개발 · 애플리케이션 보안",
    "backTop": "맨 위로",
    "workTitle": "앱, 도구, 그리고 실험",
    "workIntro": "여행, 개인 컬렉션, 학습, 투자 연구와 게임을 다루는 여섯 프로젝트입니다. 어떤 제품인지 소개하고, 설계·구현·검증 과정으로 이어집니다.",
    "archived": "개발 종료",
    "contactTitle": "연락처",
    "contactIntro": "백엔드 개발 채용, 기술 면접, 프로젝트 협업에 관한 문의는 이메일로 보내주세요.",
    "emailLabel": "EMAIL",
    "contactNote": "인증·인가, 데이터베이스 정합성, API 접근 제어와 자동화된 검증을 중심으로 프로젝트를 진행하고 있습니다.",
    "contactTopics": [
      "백엔드 개발",
      "애플리케이션 보안",
      "소프트웨어 개발"
    ],
    "projectLabel": "PROJECT NOTES",
    "caseLabel": "ENGINEERING CASE STUDY",
    "overview": "프로젝트 개요",
    "problem": "기술적 과제",
    "decision": "설계 결정",
    "implementation": "구현 내용",
    "tradeoff": "설계 시 고려사항",
    "verification": "검증 결과",
    "boundary": "구현 상태",
    "stack": "사용 기술",
    "status": "진행 상태",
    "process": "개발 방식",
    "processValue": "개인 프로젝트 · AI 활용",
    "evidenceLabel": "검증 기준",
    "evidenceNote": "2026년 9월 5~6일 확인한 소스 코드, 회귀 테스트, 개발 체크포인트를 근거로 작성했습니다. 테스트 결과는 각 사례에 명시한 환경과 시점을 기준으로 합니다.",
    "returnWork": "전체 프로젝트로",
    "nextProject": "다음 프로젝트",
    "notFoundTitle": "페이지를 찾을 수 없습니다.",
    "notFoundText": "프로젝트 목록으로 돌아가 다른 작업을 살펴보세요.",
    "heroNote": "Python · TypeScript · PostgreSQL · Firebase",
    "heroProfile": "BACKEND DEVELOPMENT / APPLICATION SECURITY",
    "aboutLabel": "04 / DEVELOPMENT PRACTICE",
    "aboutTitle": "요구사항에서 검증까지",
    "aboutText": "구현, 디버깅, 코드 리뷰에 AI를 활용합니다. 제품 요구사항을 정하고 동작을 개선하며 실패 상황의 검증을 요구하는 방식으로 프로젝트를 진행합니다. 기술 사례에는 이 과정에서 나온 설계 결정과 확인 근거를 담았습니다.",
    "investigationsLabel": "RELATED ENGINEERING WORK",
    "investigationsTitle": "추가 구현 및 검증 사례",
    "challengeLabel": "상황",
    "solutionLabel": "적용한 제어",
    "checkLabel": "검증",
    "strengthsLabel": "프로젝트 적용 기술",
    "profileLabel": "중점 분야",
    "reuseLabel": "REUSABLE ENGINEERING ASSETS",
    "reuseTitle": "사용 조건까지 함께 남기는 코드 자산",
    "reuseText": "종료한 수학 앱의 코드를 여섯 개 기능으로 분류하고 원본 소스, 의존성 목록, 관련 테스트와 한계를 함께 보관했습니다. 별도의 Dart import 경계 검사 도구에는 실행 예시와 자체 테스트가 있습니다. 후속 작업에 맞게 수정할 참고 자료로 관리하며, 다른 활성 제품에서의 실제 재사용 여부는 아직 확인되지 않았습니다.",
    "reuseLink": "코드 보관과 재사용 준비 과정 보기",
    "productLabel": "THE PRODUCT",
    "workflowLabel": "핵심 이용 흐름",
    "technicalLabel": "핵심 기술 사례",
    "invariantLabel": "반드시 지켜야 하는 조건",
    "flowLabel": "실제 처리 순서",
    "scenariosLabel": "상황별 동작과 검증",
    "scenarioLabel": "발생 상황",
    "expectedLabel": "기대 동작 · 확인 결과"
  }
};
