export const locales = ['en', 'ko'];

export const copy = {
  en: {
    siteTitle: 'JIHOON — Backend, security & independent projects',
    description: 'Independent projects by Jihoon. Explore AI-assisted work in backend systems, security boundaries, data validation, apps, and games.',
    nav: ['Work', 'Approach', 'Contact'],
    skip: 'Skip to content', menu: 'Menu', closeMenu: 'Close menu', home: 'Home',
    eyebrow: 'INDEPENDENT BUILDER · BACKEND & SECURITY',
    headline: ['Building beyond', 'the interface.'],
    intro: 'I’m Jihoon. I work with AI to turn product ideas into software, with a focus on how data moves, where access stops, and how failures are caught.',
    viewWork: 'Explore the work', contact: 'Let’s talk',
    focus: ['Backend systems', 'Security boundaries', 'Meaningful tests'],
    diagramTitle: 'A closer look at the backend',
    diagramSteps: ['Request', 'Check access', 'Change state', 'Verify behavior'],
    diagramLabels: ['Who can act?', 'What stays consistent?', 'What happens on failure?'],
    selectedLabel: '01 / SELECTED WORK', selectedTitle: 'The decisions behind the build.',
    selectedIntro: 'Four engineering case studies, from access control to tests that can actually catch a defect.',
    allWork: 'All six projects', readCase: 'Read case study', viewProject: 'Explore project',
    approachLabel: '02 / HOW I WORK', approachTitle: 'Built with AI.\nReviewed with intent.',
    approachIntro: 'AI is part of my process, from implementation to review. These projects document the requirements, engineering choices, and checks around the generated code.',
    approachItems: [
      ['Define the boundary', 'Make the allowed behavior explicit: who can access a resource, which state changes are valid, and what must be rejected.'],
      ['Examine the failure', 'Look at interrupted requests, repeated actions, conflicting updates, and malformed inputs—not just the successful path.'],
      ['Keep the evidence', 'Use regression cases and recorded checks to explain what was tested. Keep local verification and production readiness separate.'],
    ],
    moreLabel: '03 / EXPLORATIONS', moreTitle: 'Other directions, same curiosity.',
    moreIntro: 'A cooperative game and an archived learning prototype round out the project collection.',
    ctaLabel: 'HAVE SOMETHING IN MIND?', ctaTitle: 'Let’s make it work.',
    ctaText: 'For project conversations and collaboration, email me.',
    footer: 'Independent projects. Thoughtful engineering.', backTop: 'Back to top',
    workTitle: 'Projects & engineering notes.',
    workIntro: 'Apps, backend systems, research tools, and a game. Each project is labeled by its current scope, with detailed notes where the evidence supports them.',
    archived: 'Archive', contactTitle: 'Start a conversation.',
    contactIntro: 'Interested in an app, a backend problem, or an idea worth exploring? Send a little context and what you’re hoping to build.',
    emailLabel: 'EMAIL', contactNote: 'I’m especially interested in backend reliability, access control, and turning early product ideas into testable software.',
    contactTopics: ['Apps & services', 'Backend & data', 'AI-assisted development'],
    projectLabel: 'PROJECT NOTES', caseLabel: 'ENGINEERING CASE STUDY',
    overview: 'Overview', problem: 'The problem', decision: 'The decision', implementation: 'How it works',
    tradeoff: 'The tradeoff', verification: 'What was verified', boundary: 'Current scope',
    stack: 'TECHNOLOGY', status: 'STATUS', process: 'PROCESS', processValue: 'AI-assisted development',
    evidenceLabel: 'ABOUT THE EVIDENCE',
    evidenceNote: 'Sources include project code, regression tests, and development checkpoints reviewed on September 5, 2026. Verification results describe the environment and scope recorded at that time.',
    returnWork: 'Back to all projects', nextProject: 'Next project',
    notFoundTitle: 'This page isn’t here.', notFoundText: 'Head back to the project collection to keep exploring.',
  },
  ko: {
    siteTitle: 'JIHOON — 백엔드, 보안 그리고 개인 프로젝트',
    description: '이지훈의 개인 프로젝트. AI와 함께 만든 백엔드 시스템, 보안 경계, 데이터 검증, 앱과 게임의 구현 과정을 소개합니다.',
    nav: ['프로젝트', '작업 방식', '연락처'],
    skip: '본문으로 이동', menu: '메뉴', closeMenu: '메뉴 닫기', home: '홈',
    eyebrow: 'INDEPENDENT BUILDER · BACKEND & SECURITY',
    headline: ['화면 너머의', '시스템을 만듭니다.'],
    intro: '이지훈입니다. AI와 함께 아이디어를 소프트웨어로 구현합니다. 데이터의 흐름, 접근 권한의 경계, 실패를 발견하는 검증 과정에 집중합니다.',
    viewWork: '프로젝트 살펴보기', contact: '이야기 나누기',
    focus: ['백엔드 시스템', '보안 경계', '실효성 있는 테스트'],
    diagramTitle: '백엔드를 들여다보는 관점',
    diagramSteps: ['요청', '권한 확인', '상태 변경', '동작 검증'],
    diagramLabels: ['누가 실행할 수 있을까?', '무엇이 일관돼야 할까?', '실패하면 어떻게 될까?'],
    selectedLabel: '01 / SELECTED WORK', selectedTitle: '구현을 이끈 판단들.',
    selectedIntro: '접근 제어부터 결함을 잡아내는 테스트까지, 네 가지 프로젝트의 기술적 문제와 해결 과정을 정리했습니다.',
    allWork: '전체 프로젝트 6개', readCase: '기술 사례 읽기', viewProject: '프로젝트 살펴보기',
    approachLabel: '02 / HOW I WORK', approachTitle: 'AI와 만들고,\n근거를 확인합니다.',
    approachIntro: '구현과 검토 과정에 AI를 활용합니다. 각 프로젝트에는 생성된 코드와 함께 요구사항, 설계 결정, 실제로 확인한 검증 범위를 기록합니다.',
    approachItems: [
      ['경계를 먼저 정의합니다', '누가 데이터에 접근할 수 있는지, 어떤 상태 변경이 유효한지, 어떤 요청을 거부해야 하는지 명확하게 정합니다.'],
      ['실패하는 경우를 살펴봅니다', '정상 실행에 더해 요청 중단, 재시도, 동시에 일어나는 변경과 잘못된 입력을 검토합니다.'],
      ['검증 근거를 남깁니다', '회귀 테스트와 실행 기록으로 확인한 범위를 설명합니다. 로컬 검증과 운영 준비 상태는 구분해서 기록합니다.'],
    ],
    moreLabel: '03 / EXPLORATIONS', moreTitle: '다른 방향으로 이어지는 실험.',
    moreIntro: '협동 게임과 개발을 종료한 학습 프로토타입도 프로젝트 이력에 담았습니다.',
    ctaLabel: 'HAVE SOMETHING IN MIND?', ctaTitle: '함께 구체화해 봅시다.',
    ctaText: '프로젝트와 협업에 관한 이야기는 이메일로 보내주세요.',
    footer: '아이디어를 만들고, 구현의 근거를 살핍니다.', backTop: '맨 위로',
    workTitle: '프로젝트와 기술 기록.',
    workIntro: '앱, 백엔드 시스템, 연구 도구와 게임을 만들고 있습니다. 각 프로젝트의 현재 범위를 표시하고, 근거가 있는 구현은 상세 사례로 정리했습니다.',
    archived: '개발 종료', contactTitle: '이야기를 시작해 주세요.',
    contactIntro: '앱이나 백엔드의 문제, 구체화하고 싶은 아이디어가 있나요? 배경과 만들고 싶은 결과를 간단히 알려주세요.',
    emailLabel: 'EMAIL', contactNote: '백엔드의 안정성, 접근 제어, 초기 아이디어를 검증 가능한 소프트웨어로 만드는 과정에 관심이 있습니다.',
    contactTopics: ['앱과 서비스', '백엔드와 데이터', 'AI를 활용한 개발'],
    projectLabel: 'PROJECT NOTES', caseLabel: 'ENGINEERING CASE STUDY',
    overview: '프로젝트 소개', problem: '어떤 문제였나', decision: '어떻게 결정했나', implementation: '구현 방식',
    tradeoff: '선택에 따른 부담', verification: '확인한 결과', boundary: '현재 구현 범위',
    stack: '사용 기술', status: '진행 상태', process: '작업 방식', processValue: 'AI를 활용한 개발',
    evidenceLabel: '검증 기록에 관하여',
    evidenceNote: '2026년 9월 5일 확인한 프로젝트 코드, 회귀 테스트, 개발 체크포인트를 바탕으로 작성했습니다. 검증 결과는 당시 기록에 명시된 환경과 범위를 기준으로 설명합니다.',
    returnWork: '전체 프로젝트로', nextProject: '다음 프로젝트',
    notFoundTitle: '페이지를 찾을 수 없습니다.', notFoundText: '프로젝트 목록으로 돌아가 다른 작업을 살펴보세요.',
  },
};
